### ISSUE TITLE
VM46116:1 Uncaught ReferenceError: firebaseRef is not defined

### ISSUE THREAD

**Issue by spdaly** [szaranger/firebase-saga#1]
Thanks for putting this together. Working on a large project using [mxstbr/react-boilerplate](https://github.com/mxstbr/react-boilerplate) as a starter and just decided to move to Firebase.

I used the sample code in a saga.  

```
import { take, takeEvery, call, fork, cancel, put } from 'redux-saga/effects';
import { LOCATION_CHANGE } from 'react-router-redux';
import { GET_DOCUMENTS } from './constants';
import { getDocumentsSuccess, getDocumentsError } from './actions';
import * as firebaseRef from 'firebase-saga';

export function* getDocuments() {
  debugger;
  const documents = yield call(firebaseRef.get, 'documents');

  if (!documents.err) {
    yield put(getDocumentsSuccess(documents.data.results));
  } else {
    yield put(getDocumentsError(documents.err));
  }
}

export function* setWatcher() {
  while (yield take(GET_DOCUMENTS)) {
    yield call(getDocuments);
  }
}

export function* dashboardSaga() {
  const watcher = yield fork(setWatcher);
  yield take(LOCATION_CHANGE);
  yield cancel(watcher);
}

export default [
  dashboardSaga,
];
```

The saga errors out and says that firebaseRef has not been defined.

Here's a [screenshot](http://www.screencast.com/t/onQZaYRtdqUD)

**Comment by szaranger** [comment]
Hey @spdaly, could you let me know, which version of `firebase-saga` you are using?

**Comment by spdaly** [comment]
Here's a snippet from package.json...

```
    "firebase": "^3.2.1",
    "firebase-saga": "^1.0.13",
```

**Comment by szaranger** [comment]
Hi Steve,

The version seem to be correct. 
Did you check the rules of your Firebase database? 

It should have at least the read rule set:

```
{
  "rules": {
    ".read": "true",
    ".write": "auth != null"
  }
}
```

**Comment by spdaly** [comment]
I have everything wide open right now. 

```
{
  "rules": {
    ".read": true,
    ".write": true
  }
}
```

**Comment by szaranger** [comment]
Still getting the error?

**Comment by spdaly** [comment]
Yes.

**Comment by szaranger** [comment]
Can you try this code snippt in JSBin and see if your firebase config is working:

```
var app = firebase.initializeApp({
    apiKey: "xxxxx",
    authDomain: "xxxx.firebaseapp.com",
    databaseURL: "https://xxxx.firebaseio.com",
    storageBucket: "xxxx.appspot.com"
  });

var ref = firebase.database().ref('documents');
var ret = ref.once('value', function(snap){
   console.log(snap.val());
});

console.log(ret);
```

**Comment by szaranger** [comment]
Also if `document` is your top level node, you can use `getAll` method as below:

```
import {getAll} from 'firebase-saga';

const documents = yield call(getAll, 'documents');
```

**Comment by spdaly** [comment]
It's working correctly.

https://jsbin.com/sulewik/2/edit?console

**Comment by spdaly** [comment]
And...it's working...

Your note above did the trick.  firebaseRef wasn't getting defined before, but now the getAll is importing correctly.

Thanks.

**Comment by szaranger** [comment]
That's great to hear. I'll have my example updated to a full working demo in couple of days.
