### ISSUE TITLE
Using the create function

### ISSUE THREAD

**Issue by luandro** [szaranger/firebase-saga#2]
Thanks for this, a real life saver.

I'd like use Firebases `push` method, I took a look at your `create` method but couldn't make much sense on how to use it. Could you give an example?

Cheers!

**Comment by szaranger** [comment]
Hi @luandro,

Thanks for the feedback. I'm working on couple of helper methods at the moment and I'll have the `push` method ready and tested within two days.

cheers,
Sean

**Comment by luandro** [comment]
I'll keep an eye!

**Comment by szaranger** [comment]
Hi @luandro,

I've implemented `push` in `firebase-saga` version `1.0.17`. 

Here is an example usage:

```
import { push } from 'firebase-saga';

yield call(push, 'posts', () => ({
        title: 'Fourth Post',
        body: 'This is a the fourth post',
        timestamp: +new Date
    })
);
```

You can look at a full working example here: https://github.com/szaranger/firebase-saga/tree/master/examples/blog

**Comment by luandro** [comment]
Hey @szaranger, thanks!

I implemented it yesterday as well, very similar to what you did. Did you getting error handling to work?

**Comment by szaranger** [comment]
Hey @luandro,

Error handling is something I have in the pipeline.
