### ISSUE TITLE
Firebase sync?

### ISSUE THREAD

**Issue by spdaly** [szaranger/firebase-saga#3]
Does Firebase sync work?

**Comment by szaranger** [comment]
It suppose to work for `child_added` and `child_removed` events. I'm planning to implement `sync` inside the `Blog` example in couple of days. Did you have any issues getting it to work?

**Comment by szaranger** [comment]
Hey @spdaly,

I have updated the example app (https://github.com/szaranger/firebase-saga/tree/master/examples/blog) to indicate how `sync` works.

Also the `sync` helper of version `1.1.0` will be returning a key and value pair with changes for child added, removed, changed and moved.

```
import { sync, CHILD_ADDED, CHILD_REMOVED } from 'firebase-saga';

function* syncPosts() {
    yield fork(sync, 'posts', {
        [CHILD_ADDED]: actions.syncPostAdded,
        [CHILD_REMOVED]: actions.syncPostRemoved
    });
}
```
