### ISSUE TITLE
ReferenceError: firebase is not defined

### ISSUE THREAD

**Issue by bitIO** [szaranger/firebase-saga#7]
I'm getting this error 

```
ReferenceError: firebase is not defined
   at sync$ (webpack:///./~/firebase-saga/dist/ReactProxy.js?:446:18)
   ...
```

It is referring to the sync method. I don't see any import of the firebase tool in the code with the functions. 

These are my installed versions:
- "firebase": "^3.3.2",
- "firebase-saga": "^1.1.0",

Are there any special requirements to use firebase-saga?

**Comment by szaranger** [comment]
Hi @bitIO ,

It seems to be some changes they have made in the latest firebase version.

Could you remove firebase from `npm_modules` and install `3.2.0` like follows:

```
npm install --save firebase@3.2.0
```

I will have it fixed at some point, but for now I'm gonna lock the version to `3.2.x' for firebase.

**Comment by bitIO** [comment]
Ok, the _workaround_ is also to make it available by making it global (if needed). Not clean but also works 🤔

**Comment by szaranger** [comment]
Locking in the version is better in terms of avoiding different versions in global.

**Comment by bitIO** [comment]
It can be closed since it's pretty clear the issue is caused by third party lib (although it's a dependency 😝)
