### ISSUE TITLE
Minor issue in Blog example

### ISSUE THREAD

**Issue by johnmw** [szaranger/firebase-saga#9]
Hi, there appears to be a minor issue in the Blog example that threw me when I was playing with it: 

This does not look correct:

export const POST_CREATED = 'POST_RECEIVED';

here:

https://github.com/szaranger/firebase-saga/blob/master/examples/blog/src/actions/index.js#L11

(otherwise, thanks a lot, it has helped me a lot :)

**Comment by szaranger** [comment]
Thanks @johnmw for pointing out this issue. It's been fixed now. And glad to be a help :)
